language: node_js

node_js:
  - "9.11.1"

sudo: true

env:
  - CXX=g++-4.8
  - NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE USER ecarzoglio PASSWORD '123456';" -U postgres
  - psql -c "CREATE DATABASE nodetesting WITH OWNER ecarzoglio;" -U postgres
  - node_modules/.bin/sequelize db:migrate
